# Node.js React Web App to Linux on Azure
# Build a Node.js React app and deploy it to Azure as a Linux web app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: "6d4ddebb-a18f-4c1a-ac8c-60b65613c4b1"

  # Web app name
  webAppName: "devops-tutorial-cdq"

  # Environment name
  environmentName: "devops-tutorial-cdq"

  # Agent VM image name
  vmImageName: "ubuntu-latest"

stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: $(vmImageName)

        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "16.x"
            displayName: "Install Node.js"

          - task: ArchiveFiles@2
            displayName: "Archive files"
            inputs:
              rootFolderOrFile: "$(System.DefaultWorkingDirectory)"
              includeRootFolder: false
              archiveType: zip
              archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
              replaceExistingArchive: true

          - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
            artifact: drop

  - stage: Deploy
    displayName: Deploy stage
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: Deploy
        displayName: Deploy
        environment: $(environmentName)
        pool:
          vmImage: $(vmImageName)
        strategy:
          runOnce:
            deploy:
              steps:
                - task: CmdLine@2
                  displayName: "Install dependencies"
                  inputs:
                    script: |
                      cd $(Pipeline.Workspace)
                      npm install

                - task: CmdLine@2
                  displayName: "Build application"
                  inputs:
                    script: |
                      npm run build --if-present

                - task: AzureRmWebAppDeployment@4
                  displayName: "Azure App Service Deploy: devops-tutorial-cdq"
                  inputs:
                    azureSubscription: $(azureSubscription)
                    appType: webAppLinux
                    WebAppName: $(webAppName)
                    packageForLinux: "$(Pipeline.Workspace)/drop/$(Build.BuildId).zip"
                    RuntimeStack: "NODE|16-lts"
                    StartupCommand: "npm run start"
