trigger:
- main

stages:
- stage: Build
  displayName: Build and publish npm package
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'
      displayName: 'Install Node.js'
      workingDirectory: '$(Build.SourcesDirectory)'

    - script: |
        npm install
      displayName: 'npm install'
      workingDirectory: '$(Build.SourcesDirectory)'

    - script: |
        npm run build
      displayName: 'Build React application'
      workingDirectory: '$(Build.SourcesDirectory)'

    - task: PublishBuildArtifacts@1
      inputs:
        artifactName: 'zip'
        artifactType: 'container'
        pathToPublish: '$(Build.SourcesDirectory)/build'
      version: '1.*'

    - task: CopyFiles@2
      inputs:
        sourceFolder: '$(Build.SourcesDirectory)'
        contents: '*.tgz' 
        targetFolder: '$(Build.ArtifactStagingDirectory)/npm'
      displayName: 'Copy npm package'
      version: '2.*'

    - task: CopyFiles@2
      inputs:
        sourceFolder: '$(Build.SourcesDirectory)'
        contents: 'package.json' 
        targetFolder: '$(Build.ArtifactStagingDirectory)/npm'
      displayName: 'Copy package.json'
      version: '2.*'   

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/npm'
        artifactName: npm
      displayName: 'Publish npm artifact'
      version: '1.*'

- stage: Deploy
  displayName: Deploy to Azure Web App
  dependsOn: Build
  jobs:
  - job: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: 'zip'
      displayName: 'Download artifact'
      version: '2.*'

    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Azure for Students(2a5141e6-54fb-4506-b600-4eded22b4219)'
        appType: 'webApp'
        WebAppName: 'webapp-demo-pipeline'
        ResourceGroupName: 'Pipeline-Tester'
        packageForLinux: '$(Pipeline.Workspace)/zip/**/*.zip'
        UseWebDeploy: true
      displayName: 'Deploy to Azure Web App'
      version: '4.*'
